AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  An example RESTful service

Globals:
  Function:
    Timeout: 180

Resources:
  CreateLocation:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: locations/create.handler
      Events:
        CreateLocation:
          Type: Api
          Properties:
            Path: /locations
            Method: post
  ListLocations:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: locations/list.handler
      Events:
        ListLocations:
          Type: Api
          Properties:
            Path: /locations
            Method: get
  OptionsLocations:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/options.handler
      Events:
        OptionsLocations:
          Type: Api
          Properties:
            Path: /locations
            Method: options
  OptionsBookings:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/options.handler
      Events:
        OptionsBookings:
          Type: Api
          Properties:
            Path: /bookings
            Method: options
  ListSlots:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: slots/list.handler
      Events:
        ListSlots:
          Type: Api
          Properties:
            Path: /slots
            Method: get

  CreateSlot:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: slots/create.handler
      Events:
        SlotBooking:
          Type: Api
          Properties:
            Path: /slots
            Method: post

  OptionsSlots:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/options.handler
      Events:
        OptionsSlots:
          Type: Api
          Properties:
            Path: /slots
            Method: options

  OptionsBlocks:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/options.handler
      Events:
        OptionsSlots:
          Type: Api
          Properties:
            Path: /blocks
            Method: options
  CreateBlock:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: blocks/create.handler
      Events:
        CreateBlock:
          Type: Api
          Properties:
            Path: /blocks
            Method: post
  DeleteBlock:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: blocks/delete.handler
      Events:
        DeleteBlock:
          Type: Api
          Properties:
            Path: /blocks/{id}
            Method: delete

  DeleteBlockOptions:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/options.handler
      Events:
        DeleteBlockOptions:
          Type: Api
          Properties:
            Path: /blocks/{id}
            Method: options
  CreateBooking:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: bookings/create.handler
      Events:
        CreateBooking:
          Type: Api
          Properties:
            Path: /bookings
            Method: post
  CreateBookingNote:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: bookings/addNote.handler
      Events:
        CreateBookingNote:
          Type: Api
          Properties:
            Path: /bookings/{id}/notes
            Method: post
  CreateBookingNoteOptions:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/options.handler
      Events:
        CreateBookingNoteOptions:
          Type: Api
          Properties:
            Path: /bookings/{id}/notes
            Method: options
  DeleteBookingNote:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: bookings/deleteNote.handler
      Events:
        DeleteBookingNote:
          Type: Api
          Properties:
            Path: /bookings/{bookingId}/notes/{noteId}
            Method: delete
  DeleteBookingNoteOptions:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/options.handler
      Events:
        DeleteBookingNoteOptions:
          Type: Api
          Properties:
            Path: /bookings/{bookingId}/notes/{noteId}
            Method: options
  AddBookingPayment:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: bookings/addPayment.handler
      Events:
        AddBookingPayment:
          Type: Api
          Properties:
            Path: /bookings/{id}/payments
            Method: post
  AddBookingPaymentOptions:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/options.handler
      Events:
        AddBookingPaymentOptions:
          Type: Api
          Properties:
            Path: /bookings/{id}/payments
            Method: options
  OptionsBooking:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/options.handler
      Events:
        OptionsBooking:
          Type: Api
          Properties:
            Path: /bookings/{id}
            Method: options
  UpdateBooking:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: bookings/update.handler
      Events:
        UpdateBooking:
          Type: Api
          Properties:
            Path: /bookings/{id}
            Method: put
  GetBooking:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: bookings/get.handler
      Events:
        GetBooking:
          Type: Api
          Properties:
            Path: /bookings/{id}
            Method: get
  GetBookings:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: bookings/list.handler
      Events:
        ListBookings:
          Type: Api
          Properties:
            Path: /bookings
            Method: get
  GetSchedules:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/list.handler
      Events:
        ListSchedules:
          Type: Api
          Properties:
            Path: /schedules
            Method: get

  GetSchedule:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/get.handler
      Events:
        GetSchedule:
          Type: Api
          Properties:
            Path: /schedules/{id}
            Method: get

  OptionsSchedules:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/options.handler
      Events:
        ListSchedules:
          Type: Api
          Properties:
            Path: /schedules
            Method: options

  OptionsSchedule:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/options.handler
      Events:
        ListSchedules:
          Type: Api
          Properties:
            Path: /schedules/{id}
            Method: options

  CreateSchedule:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/create.handler
      Events:
        ListSchedules:
          Type: Api
          Properties:
            Path: /schedules
            Method: post
  UpdateSchedule:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/update.handler
      Events:
        ListSchedules:
          Type: Api
          Properties:
            Path: /schedules/{id}
            Method: put
  DeleteSchedule:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: schedules/delete.handler
      Events:
        ListSchedules:
          Type: Api
          Properties:
            Path: /schedules/{id}
            Method: delete

  CreateDB:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Timeout: 180
      Handler: operations/index.handler
      Events:
        CreateDB:
          Type: Api
          Properties:
            Path: /operations
            Method: get